Remove dummy notify API keys to make it easier to run locally
Using "some-api-key" results in the API not starting with the below exception

  File "/app/datahub/interaction/email_processors/processors.py", line 12, in <module>
    from datahub.interaction.email_processors.notify import (
  File "/app/datahub/interaction/email_processors/notify.py", line 10, in <module>
    from datahub.notification.notify import notify_adviser_by_email
  File "/app/datahub/notification/__init__.py", line 3, in <module>
    from datahub.notification.core import notify_gateway
  File "/app/datahub/notification/core.py", line 81, in <module>
    notify_gateway = NotifyGateway()
  File "/app/datahub/notification/core.py", line 19, in __init__
    self._initialise_clients()
  File "/app/datahub/notification/core.py", line 26, in _initialise_clients
    clients[service_name] = NotificationsAPIClient(api_key)
  File "/usr/local/lib/python3.10/site-packages/notifications_python_client/base.py", line 34, in __init__
    assert service_id, "Missing service ID"
AssertionError: Missing service ID

It's better for these environment variables to exist, but be falsy, since the
code at
https://github.com/uktrade/data-hub-api/blob/6fddf4fbdb2220f77078f1273b1fa99bddfb5b8a/datahub/notification/core.py#L25
tries to use the API keys if they're truthy, which results in the above error
from notifications_python_client.